services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "tasktracker,messagesenderdb"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tasktracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  webcli:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.webcli
    ports:
      - "5234:5234"
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=tasktracker;Username=postgres;Password=postgres
      - ENABLE_BENCHMARK=false
      - ASPNETCORE_URLS=http://+:5234
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs/webcli:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5234/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  nginx-internal:
    image: nginx
    ports:
      - "5000:5000"
    environment:
      - SECRET=$SECRET_KEY
    depends_on:
      webcli:
        condition: service_healthy
    volumes:
      - ./logs/nginx-internal:/var/log/nginx
      - ./nginx/nginx_internal.conf.template:/etc/nginx/conf.d/nginx.conf.template
      #- ./nginx/bebra.conf:/etc/nginx/nginx.conf
    #command: /bin/bash -c "envsubst '$$SECRET' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    command: >
      /bin/bash -c "
      echo 'Starting envsubst...' &&
      envsubst '$$SECRET' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf &&
      echo 'Configuration generated. Testing nginx config...' &&
      nginx -t &&
      echo 'Starting nginx...' &&
      nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  message_sender:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.messagesender
    environment:
      - BASE_URL=http://nginx-internal:5000
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=messagesenderdb;Username=postgres;Password=postgres
      - SECRET_KEY=$SECRET_KEY
      - BOT_TOKEN=$BOT_TOKEN
    depends_on:
      nginx-internal:
        condition: service_healthy
    volumes:
      - ./logs/message_sender:/app/logs
      
  nginx-external:
    image: nginx:alpine
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx_external.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/static:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./logs/nginx-external:/app/logs
    depends_on:
      nginx-internal:
        condition: service_healthy