services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "tasktracker,messagesenderdb"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tasktracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  webcli-main-1:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.webcli
    ports:
      - "5234:5234"
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=tasktracker;Username=postgres;Password=postgres
      - ENABLE_BENCHMARK=false
      - ASPNETCORE_URLS=http://+:5234
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs/webcli:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5234/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 1
      
  webcli-reader-1-1:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.webcli
    ports:
      - "5235:5235"
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=tasktracker;Username=postgres;Password=postgres
      - ENABLE_BENCHMARK=false
      - ASPNETCORE_URLS=http://+:5235
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs/webcli:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5235/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5
       
      
  webcli-reader-1-2:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.webcli
    ports:
      - "5236:5236"
    environment:
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=tasktracker;Username=postgres;Password=postgres
      - ENABLE_BENCHMARK=false
      - ASPNETCORE_URLS=http://+:5236
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs/webcli:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5236/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5
      
  nginx-internal-1:
    image: nginx:alpine
    ports:
      - "5000:5000"
    environment:
      - SECRET=$SECRET_KEY
      - MAIN_ADDRESS=webcli-main-1
      - MAIN_PORT=5234
      - READER1_ADDRESS=webcli-reader-1-1
      - READER1_PORT=5235
      - READER2_ADDRESS=webcli-reader-1-2
      - READER2_PORT=5236
      - PORT=5000
    depends_on:
      webcli-main-1:
        condition: service_healthy
      webcli-reader-1-1:
        condition: service_healthy
      webcli-reader-1-2:
        condition: service_healthy
    volumes:
      - ./logs/nginx-internal:/var/log/nginx
      - ./nginx/nginx_internal.conf.template:/etc/nginx/conf.d/nginx.conf.template
    command: >
      /bin/sh -c "
      echo 'Starting envsubst...' &&
      envsubst '$$SECRET $$MAIN_ADDRESS $$MAIN_PORT $$READER1_ADDRESS $$READER1_PORT $$READER2_ADDRESS $$READER2_PORT $PORT' 
      < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/nginx.conf &&
      echo 'Configuration generated. Testing nginx config...' &&
      nginx -t &&
      echo 'Starting nginx...' &&
      nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5
      
  message_sender:
    build:
      context: ../code
      dockerfile: ../deploy_files/Dockerfile.messagesender
    environment:
      - BASE_URL=http://nginx-internal:5000
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=messagesenderdb;Username=postgres;Password=postgres
      - SECRET_KEY=$SECRET_KEY
      - BOT_TOKEN=$BOT_TOKEN
    depends_on:
      nginx-internal-1:
        condition: service_healthy
    volumes:
      - ./logs/message_sender:/app/logs
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5
      
  nginx-external:
    image: nginx:alpine
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx_external.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/static:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./logs/nginx-external:/app/logs
    depends_on:
      nginx-internal-1:
        condition: service_healthy
    mem_limit: 256M
    mem_reservation: 128M
    cpus: 0.5