FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

# Копируем исходный код
COPY ["BD.sln", "BD.sln"]
COPY ["Domain/", "Domain/"]
COPY ["Storage/", "Storage/"]
COPY ["ShedLoadAdapter/", "ShedLoadAdapter/"]
COPY ["CLI/", "CLI/"]
COPY ["Tests/", "Tests/"]
COPY ["MessageSenderDomain/", "MessageSenderDomain/"]
COPY ["MessageSenderStorage/", "MessageSenderStorage/"]
COPY ["MessageSenderService/", "MessageSenderService/"]
COPY ["MessageSenderTaskTrackerClient/", "MessageSenderTaskTrackerClient/"]
COPY ["MessageSenderTelegramAdapter/", "MessageSenderTelegramAdapter/"]
COPY ["TaskTrackerDtoModels/", "TaskTrackerDtoModels/"]

# Восстанавливаем и строим
RUN dotnet restore "Domain/Domain.csproj" && \
    dotnet restore "Storage/Storage.csproj" && \
    dotnet restore "ShedLoadAdapter/ShedLoadAdapter.csproj" && \
	dotnet restore "CLI/CLI.csproj" && \
    dotnet restore "Tests/Tests.csproj" && \
	dotnet restore "MessageSenderDomain/MessageSenderDomain.csproj" && \
	dotnet restore "MessageSenderStorage/MessageSenderStorage.csproj" && \
	dotnet restore "MessageSenderTaskTrackerClient/MessageSenderTaskTrackerClient.csproj" && \
	dotnet restore "MessageSenderTelegramAdapter/MessageSenderTelegramAdapter.csproj" && \
	dotnet restore "MessageSenderService/MessageSenderService.csproj" && \
	dotnet restore "TaskTrackerDtoModels/TaskTrackerDtoModels.csproj"

RUN dotnet build "Domain/Domain.csproj" -c Release --no-restore && \
    dotnet build "Storage/Storage.csproj" -c Release --no-restore && \
    dotnet build "ShedLoadAdapter/ShedLoadAdapter.csproj" -c Release --no-restore && \
	dotnet build "CLI/CLI.csproj" -c Release --no-restore && \
    dotnet build "Tests/Tests.csproj" -c Release --no-restore && \
	dotnet build "MessageSenderDomain/MessageSenderDomain.csproj" -c Release --no-restore && \
	dotnet build "MessageSenderStorage/MessageSenderStorage.csproj" -c Release --no-restore && \
	dotnet build "MessageSenderTaskTrackerClient/MessageSenderTaskTrackerClient.csproj" -c Release --no-restore && \
	dotnet build "MessageSenderTelegramAdapter/MessageSenderTelegramAdapter.csproj" -c Release --no-restore && \
	dotnet build "MessageSenderService/MessageSenderService.csproj" -c Release --no-restore && \
	dotnet build "TaskTrackerDtoModels/TaskTrackerDtoModels.csproj" -c Release --no-restore

# Устанавливаем инструменты для работы с PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Запуск интеграционных тестов
ENTRYPOINT ["sh", "-c", \
  "echo 'Running E2E tests...' && \
   dotnet test Tests/Tests.csproj -c Release --no-build --filter \"Category=E2E\" --logger \"html;LogFileName=/test-results/e2e-report.html\""]