FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

# Копируем исходный код
COPY ["Domain/", "Domain/"]
COPY ["Storage/", "Storage/"]
COPY ["ShedLoadAdapter/", "ShedLoadAdapter/"]
COPY ["MessageSenderDomain/", "MessageSenderDomain/"]
COPY ["MessageSenderStorage/", "MessageSenderStorage/"]
COPY ["MessageSenderService/", "MessageSenderService/"]
COPY ["MessageSenderTaskTrackerClient/", "MessageSenderTaskTrackerClient/"]
COPY ["MessageSenderTelegramAdapter/", "MessageSenderTelegramAdapter/"]
COPY ["TaskTrackerDtoModels/", "TaskTrackerDtoModels/"]
COPY ["PublicTaskTrackerClient/", "PublicTaskTrackerClient/"]
COPY ["TaskTrackerMessageSenderClient/", "TaskTrackerMessageSenderClient/"]
COPY ["WebAPI/", "WebAPI/"]
COPY ["Tests/", "Tests/"]

# Восстанавливаем и строим только нужные проекты
RUN dotnet restore "Tests/Tests.csproj" && \

RUN "Tests/Tests.csproj" -c Release --no-restore

# Запуск unit-тестов
ENTRYPOINT ["sh", "-c", \
  "echo 'Running unit tests...' && \
   dotnet test Tests/Tests.csproj -c Release --no-build --filter \"Category=Unit\" --logger \"html;LogFileName=/test-results/unit-report.html\""]