<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<PropertyGroup>
		<XUnitMaxParallelThreads>4</XUnitMaxParallelThreads>
		<XUnitParallelizeTestCollections>true</XUnitParallelizeTestCollections>
		<XUnitDiagnosticMessages>false</XUnitDiagnosticMessages>
		<UserSecretsId>0bcc184c-5e62-46ac-a0d1-e42ee2a8c317</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Allure.Xunit" Version="2.12.1" />
		<PackageReference Include="CliWrap" Version="3.9.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.2" />
		<PackageReference Include="EntityFrameworkCore.Testing.Moq" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Telegram.Bot" Version="22.5.1" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\MessageSenderDomain\MessageSenderDomain.csproj" />
		<ProjectReference Include="..\MessageSenderStorage\MessageSenderStorage.csproj" />
		<ProjectReference Include="..\MessageSenderTaskTrackerClient\MessageSenderTaskTrackerClient.csproj" />
		<ProjectReference Include="..\MessageSenderTelegramAdapter\MessageSenderTelegramAdapter.csproj" />
		<ProjectReference Include="..\ShedLoadAdapter\ShedLoadAdapter.csproj" />
		<ProjectReference Include="..\Storage\Storage.csproj" />
		<ProjectReference Include="..\TaskTrackerMessageSenderClient\TaskTrackerMessageSenderClient.csproj" />
		<ProjectReference Include="..\WebAPI\WebAPI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<None Update="tests_settings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>